### ISSUE TITLE
Version pour tournois Fifa

### ISSUE THREAD

**Issue by thesasux** [dexterneo/ping_pong_wars#35]
Salut,

Je souhaiterais utiliser ton appli / site pour organiser un tournois Fifa. 
Pourrais tu adapter en ajoutant des fonctionnalités

**Comment by dexterneo** [comment]
Deux options : 
* Soit intégrer la gestion de différents sports dans l'appli
* Soit cloner le code et en faire une nouvelle spécialement pour le foot

Perso je partirai plus sur la deuxième

**Comment by dexterneo** [comment]
Après réflexion, je n'ajouterai pas cette feature dans l'appli et j'ai pas trop le temps de faire une autre appli à côté.

Donc fork ce repo et modifie le pour ajouter les parties FIFA et SF
